Algoritmo "Antecessor"
// Disciplina   : [Lógica de Programação]
// Professor   : Jailson Costa dos Santos
// Descrição   : Escreva um algoritmo para ler um valor (do teclado)
// e escrever (na tela) o seu antecessor.
// Autor(a)    : Lucas Moreira Nunes de Souza
// Data atual  : 02/09/2026
Var
// Seção de Declarações das variáveis 
numero: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Digite um numero :")
leia(numero)
numero<- numero-1
Escreval("Esse é seu antecessor", numero)

Fimalgoritmo