Algoritmo "L05A"
// Disciplina: [Lógica de Programação]
// Professor: Jailson Costa dos Santos
// Descrição: Apresentar os quadrados dos números inteiros de 15 a 200.
// Autor(a): Lucas Moreira Nunes de Souza
// Data atual: 26/09/2026

Var
   contador: inteiro
   quadrado_numero: inteiro

Inicio
   escreval("=========================================")
   escreval("      QUADRADOS DOS NÚMEROS (15 A 200)   ")
   escreval("=========================================")
   escreval("")

   para contador de 15 ate 200 faca
      quadrado_numero <- contador * contador
      escreval(contador, " ao quadrado = ", quadrado_numero)
   fimpara

   escreval("")
   escreval("-----------------------------------------")
   escreval("Cálculo dos quadrados concluído com sucesso!")
   escreval("-----------------------------------------")
   escreval("")

Fimalgoritmo